=pod

=for vim
   vim: tw=72 ts=3 sts=3 sw=3 et ai :

=encoding utf8

=head1 NAME

Command::Template::Runner


=head1 SYNOPSIS

   use Command::Template::Runner;


=head1 DESCRIPTION

Yadda

=head1 INTERFACE

=head2 B<< foo >>

   my $foo = foo(qw< bar baz >);


=head1 ANYTHING ELSE (INCLUDING AUTHOR, COPYRIGHT AND LICENSE)

See documentation for Command::Template.


=cut
